In [1]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv('addidas sales data.csv')
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,1/1/2020,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","$600,000","$300,000",50%,In-store
1,Foot Locker,1185732,1/2/2020,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","$500,000","$150,000",30%,In-store
2,Foot Locker,1185732,1/3/2020,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","$400,000","$140,000",35%,In-store
3,Foot Locker,1185732,1/4/2020,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"$382,500","$133,875",35%,In-store
4,Foot Locker,1185732,1/5/2020,Northeast,New York,New York,Men's Apparel,$60.00,900,"$540,000","$162,000",30%,In-store

In [4]:
df.columns

Index(['Retailer', 'Retailer ID', 'Invoice Date', 'Region', 'State', 'City',
       'Product', 'Price per Unit', 'Units Sold', 'Total Sales',
       'Operating Profit', 'Operating Margin', 'Sales Method'],
      dtype='object')

In [5]:
df['sales'] = df['Total Sales'].replace('[\$,]', '', regex=True).astype(int)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\G705728\AppData\Local\Temp\ipykernel_41128\3107900257.py:1: SyntaxWarning: invalid escape sequence '\$'
  df['sales'] = df['Total Sales'].replace('[\$,]', '', regex=True).astype(int)

In [6]:
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,sales
0,Foot Locker,1185732,1/1/2020,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","$600,000","$300,000",50%,In-store,600000
1,Foot Locker,1185732,1/2/2020,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","$500,000","$150,000",30%,In-store,500000
2,Foot Locker,1185732,1/3/2020,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","$400,000","$140,000",35%,In-store,400000
3,Foot Locker,1185732,1/4/2020,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"$382,500","$133,875",35%,In-store,382500
4,Foot Locker,1185732,1/5/2020,Northeast,New York,New York,Men's Apparel,$60.00,900,"$540,000","$162,000",30%,In-store,540000

In [8]:
df_walmart=df[df['Retailer']=='Walmart']

In [10]:
df_walmart.head()
df_walmart.describe()

        Retailer ID          sales
count  6.260000e+02     626.000000
mean   1.173732e+06  119102.891374
std    3.082033e+04  185747.169181
min    1.128299e+06     880.000000
25%    1.128299e+06    6448.500000
50%    1.185732e+06   11271.000000
75%    1.197831e+06  206250.000000
max    1.197831e+06  825000.000000

In [12]:
df_walmart['Invoice Date'] = pd.to_datetime(df_walmart['Invoice Date'])
df_walmart.dtypes

C:\Users\G705728\AppData\Local\Temp\ipykernel_41128\1195972585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_walmart['Invoice Date'] = pd.to_datetime(df_walmart['Invoice Date'])

Retailer                    object
Retailer ID                  int64
Invoice Date        datetime64[ns]
Region                      object
State                       object
City                        object
Product                     object
Price per Unit              object
Units Sold                  object
Total Sales                 object
Operating Profit            object
Operating Margin            object
Sales Method                object
sales                        int64
dtype: object

In [13]:
df_walmart['year']=df_walmart['Invoice Date'].dt.year
df_walmart['month']=df_walmart['Invoice Date'].dt.month
df_walmart['day']=df_walmart['Invoice Date'].dt.day
df_walmart.head()

C:\Users\G705728\AppData\Local\Temp\ipykernel_41128\3109624348.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_walmart['year']=df_walmart['Invoice Date'].dt.year
C:\Users\G705728\AppData\Local\Temp\ipykernel_41128\3109624348.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_walmart['month']=df_walmart['Invoice Date'].dt.month
C:\Users\G705728\AppData\Local\Temp\ipykernel_41128\3109624348.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_walmart['day']=df_walmart['Invoice Date'].dt.day

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,sales,year,month,day
46,Walmart,1185732,2020-04-17,Northeast,New York,New York,Men's Apparel,$60.00,900,"$540,000","$162,000",30%,Outlet,540000,2020,4,17
47,Walmart,1185732,2020-04-18,Northeast,New York,New York,Women's Apparel,$65.00,"1,075","$698,750","$174,688",25%,Outlet,698750,2020,4,18
48,Walmart,1185732,2020-04-19,Northeast,New York,New York,Men's Street Footwear,$60.00,"1,200","$720,000","$360,000",50%,Outlet,720000,2020,4,19
49,Walmart,1185732,2020-04-20,Northeast,New York,New York,Men's Athletic Footwear,$55.00,"1,000","$550,000","$165,000",30%,Outlet,550000,2020,4,20
50,Walmart,1185732,2020-04-21,Northeast,New York,New York,Women's Street Footwear,$50.00,925,"$462,500","$161,875",35%,Outlet,462500,2020,4,21

In [15]:
df_walmart['year'].unique()

array([2020, 2021], dtype=int32)

In [16]:
df_walmart['month'].unique()

array([ 4,  5,  7,  8,  9, 10, 11, 12,  6,  2,  3], dtype=int32)

In [17]:
df_walmart_2020=df_walmart[df_walmart['year']==2020]
df_walmart_2020['month'].unique()

array([ 4,  5,  7,  8,  9, 10], dtype=int32)

In [18]:
df_walmart_2021=df_walmart[df_walmart['year']==2021]
df_walmart_2021['month'].unique()

array([ 8,  9, 10, 11, 12,  4,  5,  6,  7,  2,  3], dtype=int32)

In [22]:
df_walmart_2021=df_walmart_2021[df_walmart_2021['month'].isin([7,8,9,10])]
df_walmart_2021['month'].unique()

array([ 8,  9, 10,  7], dtype=int32)

In [24]:
#Retailer name is walmart 
# set 1 is july-aug-sept-oct 2020
# set 2 is july-aug-sept-oct 2021
df_walmart_2021.to_csv('new_data.csv',index=False)
df_walmart_2020.to_csv('old_data.csv',index=False)